services:
  psql:
    image: postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  wallet:
    image: wallet
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_CONFIG_LOCATION: /app/config/application.yml
      SPRING_DATASOURCE_URL: jdbc:postgresql://psql:5432/app_db
      SPRING_LIQUIBASE_CHANGELOG: file:/app/config/db/changelog/db.changelog-master.yaml
    volumes:
      - ./src/main/resources:/app/config
    depends_on:
      - psql
    restart: on-failure